import {it,expect,vi} from 'vitest';import pino from 'pino';
import {createApp} from '../src/api/app.js';import {loadConfig} from '../src/config.js';import {SourceError} from '../src/sources/searchfloor/client.js';
const config=()=>loadConfig({PUBLIC_BASE_URL:'https://opds.example',CACHE_PATH:':memory:',OPDS_USERNAME:'reader',OPDS_PASSWORD:'testing-only'});
const authorization='Basic '+Buffer.from('reader:testing-only').toString('base64');
const setup=()=>{const page=vi.fn(async()=>({books:[],nextPage:2,observedAt:'2026-10-04T00:00:00Z',stale:false}));const app=createApp({config:config(),catalog:{page,book:async()=>null},log:pino({enabled:false})});return {app,page}};
it('validates config without echoing secrets',()=>{expect(()=>loadConfig({})).toThrow('Invalid configuration');expect(()=>loadConfig({...config(),PUBLIC_BASE_URL:'http://host'})).toThrow();});
it('serves static root, discovery, independent health and valid UTF-8 search',async()=>{const {app,page}=setup();expect((await app.request('/health')).status).toBe(200);const root=await app.request('/opds',{headers:{authorization}});expect(root.headers.get('content-type')).toContain('kind=navigation');expect(await root.text()).toContain('/opds/searchfloor');const result=await app.request('/opds/searchfloor/search?q=%20книга%20&page=2',{headers:{authorization}});expect(result.status).toBe(200);expect(page).toHaveBeenCalledWith('книга',2,expect.any(AbortSignal));expect(result.headers.get('content-type')).toContain('charset=utf-8');});
it('rejects invalid input and unknown/reserved sources without fetching',async()=>{const {app,page}=setup();for(const path of ['/opds/unknown/search?q=x','/opds/searchfloor/authors','/opds/searchfloor/genres/1'])expect((await app.request(path,{headers:{authorization}})).status).toBe(404);for(const path of ['/opds/searchfloor/completed?page=1.5','/opds/searchfloor/completed?page=10001','/opds/searchfloor/search?q='+ '😀'.repeat(201)])expect((await app.request(path,{headers:{authorization}})).status).toBe(400);expect(page).not.toHaveBeenCalled();});
it('returns a controlled source status and no upstream detail',async()=>{const {app,page}=setup();page.mockRejectedValue(new SourceError('secret upstream detail',502));const response=await app.request('/opds/searchfloor/completed',{headers:{authorization}});expect(response.status).toBe(502);expect(await response.text()).not.toContain('secret');});
